### ISSUE TITLE
error while running python data/preprocessing/preprocess.py

### ISSUE THREAD

**Issue by bharathdpv** [kinggongzilla/ai-clone-whatsapp#1]
**issue 1:    error while running python data/preprocessing/preprocess.py**

traceback (most recent call last):
  File "/content/ai-clone-whatsapp/data/preprocessing/preprocess.py", line 127, in <module>
    folder_to_csv(f"{args.data_folder}/train", f"{args.output_folder}/train/train_chats.csv")
  File "/content/ai-clone-whatsapp/data/preprocessing/preprocess.py", line 90, in folder_to_csv
    with open(csv_path, "w") as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/preprocessing/processed_chats/train/train_chats.csv'

![image](https://github.com/kinggongzilla/ai-clone-whatsapp/assets/101401135/193248d0-1259-4f6d-85dc-9474c4e7b836)

**issue 2: my WhatsApp export  .txt looks different!** 
![image](https://github.com/kinggongzilla/ai-clone-whatsapp/assets/101401135/2d8c6655-8cb2-4f46-9111-598ca2282939)

can you show me the example of output.csv!     as example.csv 

so that i can write my own code for parsing WhatsApp data

**Comment by kinggongzilla** [comment]
Hi!
Here is an example of the preprocessed CSV. Hope it helps. 
I am assuming that your first issue also stems from the fact that the your WhatsApp exports look different. Let me know if you still have issues.

[train_chats.csv](https://github.com/kinggongzilla/ai-clone-whatsapp/files/13793272/train_chats.csv)

**Comment by bharathdpv** [comment]
thanks kinggongzilla, i just created folder and it works , i dont understand why our WhatsApp exported chats looks different ,what os your are using?

**Comment by kinggongzilla** [comment]
OK great to hear!
I'm on iOS

**Comment by bharathdpv** [comment]
may i know where  the trained model will be ?
![image](https://github.com/kinggongzilla/ai-clone-whatsapp/assets/101401135/a4eb7e55-f294-49e2-b1ba-d9433cd54343)

**Comment by kinggongzilla** [comment]
You can specify an output directory in configs/training.py

Default currently is "checkpoints". But I just realized that the empty "checkpoints" folder wasn't committed to the repo. Will fix it

**Comment by kinggongzilla** [comment]
@bharathdpv You can either create an empty "checkpoints" directory yourself in the root folder of the repository, or you can pull my latest commit.

After training the checkpoints directory should look like this with the saved adapters (models).

<img width="316" alt="Screenshot 2023-12-29 at 15 20 05" src="https://github.com/kinggongzilla/ai-clone-whatsapp/assets/30088687/d9a92f24-48b8-4f0c-9165-4cf52907c258">

**Comment by bharathdpv** [comment]
Thanks man will try...

**Comment by nachitodev** [comment]
hey @bharathdpv what did you modify in the preprocess.py to use that whatsapp format?
